"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const group_controls_1 = require("../controllers/group-controls");
const authentication_1 = require("../middlewears/authentication");
const router = (0, express_1.Router)();
router.post("/create-group", authentication_1.authenticate, group_controls_1.createGroup);
router.post("/add-member", authentication_1.authenticate, group_controls_1.addMember);
router.post("/get-group", authentication_1.authenticate, group_controls_1.getGroup);
router.get("/get-groups", authentication_1.authenticate, group_controls_1.getGroups);
router.get("/get-users", authentication_1.authenticate, group_controls_1.getUsers);
router.get("/get-group-members", authentication_1.authenticate, group_controls_1.findGroupMembers);
router.delete("/remove-group-member", authentication_1.authenticate, group_controls_1.removeGroupMember);
exports.default = router;
